DROP TABLE IF exists customer cascade;

CREATE TABLE customer AS SELECT * FROM CSVREAD('classpath:user.csv');

/*create table user_table (
    id bigint generated by default as identity,
    login varchar(255) not null,
    name varchar(255) not null,
    genre varchar(255) not null,
    primary key (id)
);*/

INSERT INTO customer (login, name, genre) values
('1', 'Don', 'COMEDY');