grpc:
  server:
    port: 7575

server:
  port: 8081

spring:
  h2:
    console.enabled: true
  datasource:
    url: "jdbc:h2:mem:testdb"
  driverClassName: "org.h2.Driver"
  jpa:
    defer-datasource-initialization: true
    database-platform: "org.hibernate.dialect.H2Dialect"